[default]
DATABASE = {name='example.db',engine='peewee.SqliteDatabase'}
MIGRATIONS_DIR = 'models/migrations'

PEEWEE_DATABASE_URI = ''
TITLE = "Agropec"
SECRET_KEY = "hvbdgvhbsdhj"
EXTENSIONS = [
    "agropec.ext.database",
    "agropec.ext.appearance",

    "agropec.blueprints.webui"
]

[production]
PEEWEE_DATABASE_URI = ''
