# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: negotiation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11negotiation.proto\"!\n\x0b\x44\x61taSummary\x12\x12\n\nchain_size\x18\x01 \x01(\x03\"$\n\x07Package\x12\x0b\n\x03sum\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"6\n\nCollection\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1a\n\x08packages\x18\x02 \x03(\x0b\x32\x08.Package\"2\n\x0e\x43ollectionList\x12 \n\x0b\x63ollections\x18\x02 \x03(\x0b\x32\x0b.Collection\"\x8f\x01\n\x05\x42lock\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.BlockType\x12\x0b\n\x03sum\x18\x02 \x01(\t\x12$\n\ncollection\x18\x03 \x01(\x0b\x32\x0b.CollectionH\x00\x88\x01\x01\x12\x1e\n\x07package\x18\x04 \x01(\x0b\x32\x08.PackageH\x01\x88\x01\x01\x42\r\n\x0b_collectionB\n\n\x08_package\"$\n\nBlockChain\x12\x16\n\x06\x62locks\x18\x02 \x03(\x0b\x32\x06.Block*(\n\tBlockType\x12\x0e\n\nCOLLECTION\x10\x00\x12\x0b\n\x07PACKAGE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'negotiation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCKTYPE._serialized_start=386
  _BLOCKTYPE._serialized_end=426
  _DATASUMMARY._serialized_start=21
  _DATASUMMARY._serialized_end=54
  _PACKAGE._serialized_start=56
  _PACKAGE._serialized_end=92
  _COLLECTION._serialized_start=94
  _COLLECTION._serialized_end=148
  _COLLECTIONLIST._serialized_start=150
  _COLLECTIONLIST._serialized_end=200
  _BLOCK._serialized_start=203
  _BLOCK._serialized_end=346
  _BLOCKCHAIN._serialized_start=348
  _BLOCKCHAIN._serialized_end=384
# @@protoc_insertion_point(module_scope)
